config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get '/about' => 'pages#about'
  
  resources :users do
    resource :profile do
      resources :educations
      resources :experiences
      resources :projects
      resources :certificates
      get '/del-img' => 'profiles#del_img'
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_one :profile
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    # before_action :authenticate_user!
    def show
        @user = User.find(params[:id])
        @profile = @user.profile
        @education = @profile.educations
        @experience = @profile.experiences
        @project = @profile.projects
        @certificate = @profile.certificates
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_certificate.html.erb
<h3>Certificates:</h3>
<table class="table ">
    <thead>
        <tr>
          <th scope="col">Image</th>
          <th scope="col">Title</th>
          <th scope="col">Institute</th>
        </tr>
    </thead>
    <tbody>
        <% @certificate.each do |certificate| %>
            <tr>
              <td><%= image_tag certificate.avatar.url(:thumb) %></td>
              <td><%= certificate.title.capitalize %></td>
              <td><%= certificate.institute.capitalize %></td>
              <td><%= link_to "View", user_profile_certificate_path(params[:id], certificate), class:"btn btn-default btn-sm" %>
               <% if user_signed_in? && current_user == @user %>
                  <%= link_to "Edit", edit_user_profile_certificate_path(current_user, certificate), class: "btn btn-info btn-sm" %>
                  <%= link_to "Delete", user_profile_certificate_path(current_user, certificate), class: "btn btn-info btn-sm", method: "delete" %>
              <% end %></td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/users/_education.html.erb
<h3>Educations:</h3>
<table class="table">
    <thead>
        <tr>
          <th scope="col">Title</th>
          <th scope="col">Institute</th>
          <th scope="col">Year of Graduation</th>
        </tr>
    </thead>
    <tbody>
        <% @education.each do |education| %>
            <tr>
              <td><%= education.title %></td>
              <td><%= education.institute %></td>
              <td><%= education.year_of_graduation %></td>
              <% if user_signed_in? && current_user == @user %>
                  <td><%= link_to "Edit", edit_user_profile_education_path(current_user, education), class: "btn btn-info btn-sm" %></td>
                  <td><%= link_to "Delete", user_profile_education_path(current_user, education), class: "btn btn-info btn-sm", method: "delete" %></td>
              <% end %>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/users/_experience.html.erb
<% i = 1 %>       
<% @experience.each do |experience| %>
    <div class="well content exp-color">
        <h3>Experience - <%= i %></h3>
        <table class="table table-bordered">
            <tbody>
                <tr>
                    <th scope="row">Company Name:</th>
                    <td><%= experience.company_name %> </td>
                </tr>
                <tr>
                    <th scope="row">Position Title:</th>
                    <td><%= experience.position_title %> </td>
                </tr>
                <tr>
                    <th scope="row">Start Date:</th>
                    <td><%= experience.start_month %>- <%= experience.start_year %> </td>
                </tr>
                <tr>
                    <th scope="row">End Date:</th>
                    <td>
                        <% if experience.end_month == nil%>
                            Present
                        <% else %>
                            <%= experience.end_month %>- <%= experience.end_year %>
                        <% end %>
                    </td>
                </tr>
                <tr>
                    <th scope="row">Tasks description:</th>
                    <td><%= experience.tasks_description %> </td>
                </tr>
            </tbody>
        </table>
        <% if user_signed_in? && current_user == @user %>
            <div class="row">
                <div class="col-md-4 col-md-offset-8 add ">
                    <%= link_to "Edit", edit_user_profile_experience_path(current_user, experience), class: "btn btn-info" %>
                    <%= link_to "Delete", user_profile_experience_path(current_user, experience), class: "btn btn-info", method: "delete" %>
                </div>
            </div>
        <% end %>
    </div>
    <% i = i+1 %>
<% end %>

app/views/users/_project.html.erb
<h3>Projects:</h3>
<table class="table">
    <thead>
        <tr>
          <th scope="col">Image</th>
          <th scope="col">Title</th>
        </tr>
    </thead>
    <tbody>
        <% @project.each do |project| %>
            <tr>
              <td><%= image_tag project.avatar.url(:thumb) %></td>
              <td><%= project.title %></td>
              <td><%= link_to "Details", user_profile_project_path(params[:id], project),class: "btn btn-default btn-sm" %>
               <% if user_signed_in? && current_user == @user %>
                  <%= link_to "Edit", edit_user_profile_project_path(current_user, project), class: "btn btn-info btn-sm" %>
                  <%= link_to "Delete", user_profile_project_path(current_user, project), class: "btn btn-info btn-sm", method: "delete" %>
              <% end %></td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/users/show.html.erb
<div class="row">
    <div class="col-md-3 text-center user-image">
        <%= image_tag @profile.avatar.url(:thumb) %>
        <% if user_signed_in? && current_user == @user %>
            <%= link_to "delete image" , del_img_user_profile_path(current_user), class: "btn btn-info btn-sm" %>
        <% end %>
        <div class="well contact-info bg-color">
            <h4><%= @profile.first_name.capitalize %> <%= @profile.last_name.capitalize %></h4>
            <% if @profile.profession != "" %>
                 <h6><%= @profile.profession.capitalize %></h6>
            <% end %>
            <div class="personal-info ">
                <h5><%= @profile.country.capitalize %> 
                <% if @profile.city != "" %>
                    - <%= @profile.city.capitalize %>
                <% end %>
                </h5>
                <i class="fas fa-globe"></i>
            </div>
            <div class="personal-info ">
                <h5><%= @profile.phone_number %></h5>
                <i class="fas fa-phone"></i>
            </div>
            <div class="personal-info ">
                <h5><%= @profile.contact_email %></h5>
                <i class="fas fa-at"></i>
            </div>
        </div>
    </div>
    
    
    <div class="col-md-7 profile-content">
        
        <% if @profile.background_overview != "" %>
        
            <div class="well content bg-color">
                <h3>About me:</h3>
                <%= @profile.background_overview %>
            </div>
        <% end %>
        
        <!--------------------->
        <!--education section-->
        <!--------------------->
        <% if user_signed_in? && current_user == @user %>
                <div class="well content bg-color">
                    <%= render "education" %>
                    <div class="row justify-content-end">
                            <div class="col-md-4 col-md-offset-8 add ">
                                <%= link_to "Add Education", new_user_profile_education_path(current_user), class: "btn btn-info" %>
                            </div>
                        </div>
                </div>
        <% else %>
            <% if @education != []%>
                <div class="well content bg-color">
                    <%= render "education" %>
                </div>
            <% end %>
        <% end %>
        
        <!--------------------->
        <!--experience section-->
        <!--------------------->
        
            <% if user_signed_in? && current_user == @user %>
                <div class="well bg-color">
                    <div class="well content exp-color ">
                        <h3>Professional Experience:</h3>
                    </div>
                    <%= render "experience" %>
                    <div class="row justify-content-end">
                        <div class="col-md-4 col-md-offset-8 add ">
                            <%= link_to "Add Experience", new_user_profile_experience_path(current_user), class: "btn btn-info" %>
                        </div>
                    </div>
                </div>
                <% else %>
                    <% if @experience != []%>
                        <div class="well bg-color">
                            <div class="well content exp-color">
                                <h3>Professional Experience:</h3>
                            </div>
                            <%= render "experience" %>
                        </div>
                    <% end %>
                
            <% end %>
        
        
        <!--------------------->
        <!--Projects-->
        <!--------------------->
        
        <% if user_signed_in? && current_user == @user %>
        
            <div class="well content bg-color">
                <%= render "project" %>
                <div class="row justify-content-end">
                        <div class="col-md-4 col-md-offset-8 add ">
                            <%= link_to "Add Project", new_user_profile_project_path(current_user), class: "btn btn-info" %>
                        </div>
                </div>
            </div>
        <% else %>
            <% if @project != []%>
                <div class="well content bg-color">
                    <%= render "project" %>
                </div>
            <% end %>
        <% end %>
        
        <!--------------------->
        <!--Certificates-->
        <!--------------------->
        
        <% if user_signed_in? && current_user == @user %>
        
            <div class="well content bg-color">
                <%= render "certificate" %>
                <div class="row justify-content-end">
                        <div class="col-md-4 col-md-offset-8 add ">
                            <%= link_to "Add Certificate", new_user_profile_certificate_path(current_user), class: "btn btn-info" %>
                        </div>
                </div>
            </div>
        <% else %>
            <% if @certificate != []%>
                <div class="well content bg-color">
                    <%= render "certificate" %>
                </div>
            <% end %>
        <% end %>
        
        <!--------------------->
        <!--social Media-->
        <!--------------------->
        
        <% if @profile.fb_link != "" ||  @profile.lkd_link != "" ||  @profile.github_link != "" %>
            <div class="well content bg-color">
                <h3>Social Media:</h3>
                <div class="social-links">
                    <% if @profile.fb_link != "" %>
                        <a href="<%= @profile.fb_link %>"><i class="fab fa-facebook-square fa-2x"></i></a>
                    <% end %>
                    <% if @profile.lkd_link != "" %>
                        <a href="<%= @profile.lkd_link %>"><i class="fab fa-linkedin fa-2x"></i></a>
                    <% end %>
                    <% if @profile.github_link != "" %>
                        <a href="<%= @profile.github_link %>"><i class="fab fa-github-square fa-2x"></i></a>
                    <% end %>
                </div>
            </div>
        <% end %>
    
    
    </div>
    
</div>