config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get '/about' => 'pages#about'
  
  resources :users do
    resource :profile do
      resources :educations
      resources :experiences
      resources :projects
      resources :certificates
      get '/del-img' => 'profiles#del_img'
    end
  end

end

app/views/pages/about.html.erb
<div class="row">
    <div class="col-md-8 col-md-offset-2 well bg-color">
        <p>S-portfolio is an online platform to buid your personal Portfolio and share it with the WEB, your profile will help you get hired by sharing your background, education, experiences and skills with hiring companies Worldwide</p>
    </div>
</div>

app/views/pages/home.html.erb
<div class="jumbotron text-center">
    <h1>Welcome to S-Portfolio</h1>
    <% if user_signed_in? %>
        <% if current_user.profile %>
        
        <% else %>
            <%= link_to "create your profile", new_user_profile_path(current_user), class: "btn btn-info btn-lg custom-width" %>
        <% end %>
       
    <% else %>
        <h3>Create your account and build your portfolio</h3>
        <%= link_to "Sign Up Now", new_user_registration_path, class: "btn btn-info btn-lg custom-width" %>
    <% end %>
</div>
<% if user_signed_in? %>
    <% if current_user.profile %>
        <div class="row">
            <div class="well col-md-4 bg-color">
                <h2 class="text-center">My Profile</h2>
                <%= link_to "View Profile", user_path(current_user), class: "btn btn-info btn-lg btn-block" %>
                <%= link_to "Edit your profile", edit_user_profile_path(current_user), class: "btn btn-info btn-lg btn-block" %>
                <%= link_to "delete profile", user_profile_path(current_user), class: "btn btn-info btn-lg btn-block", method: "delete" %>
            </div>
        </div>
    <% end %>
<% end %>

app/views/pages/links.html.erb
 <%= link_to "Edit your profile", edit_user_profile_path(current_user), class: "btn btn-info btn-lg custom-width" %>
         <%= link_to "Education", new_user_profile_education_path(current_user), class: "btn btn-info btn-lg custom-width" %>
         <%= link_to "Experience", new_user_profile_experience_path(current_user), class: "btn btn-info btn-lg custom-width" %>
         <%= link_to "projects", new_user_profile_project_path(current_user), class: "btn btn-info btn-lg custom-width" %>