config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get '/about' => 'pages#about'
  
  resources :users do
    resource :profile do
      resources :educations
      resources :experiences
      resources :projects
      resources :certificates
      get '/del-img' => 'profiles#del_img'
    end
  end

end

app/models/education.rb
class Education < ActiveRecord::Base
    belongs_to :profile
    validates :title, presence: true
    validates :institute, presence: true
    validates :year_of_graduation, presence: true
end

app/controllers/educations_controller.rb
class EducationsController < ApplicationController
    before_action :authenticate_user!        #authenticate_user is a devise method
    before_action :only_current_user
    before_action :check_available ,except: [:new, :create]
    def new
        @profile = User.find(params[:user_id]).profile
        @education = Education.new 
      
    end
    
    def create
       @profile = User.find(params[:user_id]).profile
       @education = Education.new(education_params) 
       @education.profile_id = @profile.id
       
       if @education.save
           flash[:success] = "Education Added"
           redirect_to user_path(current_user)
       else
            flash[:danger] = 'Error occured, Input all fields.'
            render action: :new
       end
    end
    
    def edit
        @profile = User.find(params[:user_id]).profile
        @education = Education.find(params[:id])
    end
    
    def update
        @profile = User.find(params[:user_id]).profile
        @education = Education.find(params[:id])
        if @education.update_attributes(education_params)
            flash[:success] = "Education Updated!"
            redirect_to user_path(current_user)
        else
            render action: :edit
        end
    end
    
    def destroy
        @profile = User.find(params[:user_id]).profile
        @education = Education.find(params[:id])
        if @education.delete
            flash[:success] = "Education deleted!"
             redirect_to user_path(current_user)
        end
    end
     private
        def education_params
            params.require(:education).permit(:title, :institute, :year_of_graduation)
        end
        def only_current_user
            @user = User.find(params[:user_id])
            redirect_to(root_url) unless @user == current_user
        end
        def check_available
            @user = User.find(params[:user_id])
            @profile = @user.profile
            redirect_to(root_url) unless @profile.educations !=[]
        end
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/views/educations/_form.html.erb
 <%= form_for @education, url: user_profile_education_path, html: { multipart: true } do |f| %>
                <div class="form-group">
                    <%= f.label :title %>
                    <%= f.text_field :title, class:"form-control" %>
                </div>
                <div class="form-group">
                    <%= f.label :institute %>
                    <%= f.text_field :institute, class:"form-control" %>
                </div>
               
                
                <div class="form-group">
                    <%= f.label :year_of_graduation %>
                    <%= f.number_field :year_of_graduation, class:"form-control" %>
                </div>

                <div class="form-group">
                    <%= f.submit "Update", class: "btn btn-primary" %>
                </div>
            <% end %>

app/views/educations/edit.html.erb
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="well bg-color">
            <h2 class="text-center">Edit Education</h2>
          <%= render 'form' %>
        </div>
    </div>
</div>

app/views/educations/new.html.erb
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="well bg-color">
            <h2 class="text-center">Add Education</h2>
           <%= form_for @education, url: user_profile_educations_path, html: { multipart: true } do |f| %>
                <div class="form-group">
                    <%= f.label :title %>
                    <%= f.text_field :title, class:"form-control",required: true %>
                </div>
                <div class="form-group">
                    <%= f.label :institute %>
                    <%= f.text_field :institute, class:"form-control",required: true %>
                </div>
               
                
                <div class="form-group">
                    <%= f.label :year_of_graduation %>
                    <%= f.number_field :year_of_graduation, class:"form-control",required: true %>
                </div>

                <div class="form-group">
                    <%= f.submit "Add", class: "btn btn-primary" %>
                </div>
                
            <% end %>
        </div>
    </div>
</div>