config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get '/about' => 'pages#about'
  
  resources :users do
    resource :profile do
      resources :educations
      resources :experiences
      resources :projects
      resources :certificates
      get '/del-img' => 'profiles#del_img'
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>S-Portfolio</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-static-top bg-color" role="navigation">
      <div class='container'>
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to root_path, class: 'navbar-brand' do %>
            <i class="fab fa-stripe-s c-white"></i>
            <span class="c-white">- Portfolio</span>
          <% end %>
        </div>
        <div class="collapse navbar-collapse" id="main-nav-collapse">
          <div class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <%= button_to "Sign out", destroy_user_session_path, class: "btn btn-info navbar-btn", method: :delete %> <!--no need to add method -->
            <% else %>
              <%= link_to "Log in", new_user_session_path, class: "btn btn-info navbar-btn", method: :get %>
              
            <% end%>
          </div>
          <ul class="nav navbar-nav navbar-right ">
            <% if user_signed_in? %>
              <% if current_user.profile %>
                <li><%= link_to "My profile",  user_path(current_user) %></li>
              <% else %>
                <li><%= link_to "Create profile",  new_user_profile_path(current_user) %></li>
              <% end %>
              <li><%= link_to "My Account",  edit_user_registration_path %></li>
            <% end%>
            <li><%= link_to "About", about_path %></li>
            
          </ul>
          
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>
    
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag :div, value, class: "alert alert-#{key}" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>